### ISSUE TITLE
iTerm support?

### ISSUE THREAD

**Issue by alxhghs** [es-kumagai/OpenTerminal#1]
Hello! I love your program. Is there a way to set the terminal to iTerm instead of terminal.app?

**Comment by es-kumagai** [comment]
Hello🙂

Now released new version. You can use iTerm2 instead of terminal.app.
Please replase the new version (1.1.0), then execute following command at once:

```
defaults write jp.ez-style.appid.OpenTerminal ESTargetTerminalBundleIdentifier "com.googlecode.iterm2"
```

More details, please see `README.md`.
Thank you !
