### ISSUE TITLE
Open Terminal if files are selected

### ISSUE THREAD

**Issue by ygorg** [es-kumagai/OpenTerminal#2]
Sometimes it is impossible to not select anything in a Finder window :
![open_term](https://user-images.githubusercontent.com/16778267/41934368-d74aa6e8-7986-11e8-83a3-a64d4fad42fd.gif)

It would be useful to open a Terminal at the shown directory if files are selected.
The behaviour should not change if directories are selected.

**Comment by es-kumagai** [comment]
That makes sence 🙂

So, I merged your PR (#3, #4) 
Thank you so much !
